const x =10

try{
x=2
}catch(erro){
    console.log(erro)
}